sudo: required
services:
  - docker # we want docker to be pre-installed as soon as we run over build
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1  # google cloud does not show any prompt
before_install: # below two commands setup google cloud locally in your machine
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null #download and install google cloud sdk
  - source $HOME/google-cloud-sdk/path.bash.inc # $HOME/google-cloud-sdk is default installation directory and source the file  path.bash.inc
  - gcloud components update kubectl # this will install and update kubectl inside our travis env
  - gcloud auth activate-service-account --key-file service-account.json # we have to do authorization with the google cloud
  - gcloud config set project multi-k8s-293014
  - gcloud config set compute/zone us-central1-c	
  - gcloud container clusters get-credentials multi-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t sravan13/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sravan13/react-test npm test

deploy:
  provider:  script
  script: bash ./deploy.sh 
  on:
    branch: main

